go-vela/vela-kaniko

- Dockerfile
You can find a full list of release notes here:
https://github.com/GoogleContainerTools/kaniko/releases/tag/v0.20.0
> chore: upgrade Kaniko to v0.20.0

- Dockerfile
You can find a full list of release notes here:
https://github.com/GoogleContainerTools/kaniko/releases/tag/v0.21.0
> chore: upgrade Kaniko to v0.21.0

- Dockerfile
Kaniko is release notes for v1.0.0:
https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.0.0
> chore: update kaniko to latest release

- Dockerfile
Release notes for version:
https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.2.0
> chore: update to latest kaniko release

- .github/workflows/prerelease.yml
- .github/workflows/publish.yml
- Makefile
- cmd/vela-kaniko/main.go
- go.mod
- go.sum
- version/version.go
Dependent on https://github.com/go-vela/types/pull/112
Updating to the new `go-vela/types/version` package to improve the information provided surrounding the application.
When I run `make run` locally, here is the output:
```json
{
"canonical": "v0.5.0",
"major": 0,
"minor": 5,
"patch": 0,
"metadata": {
"architecture": "amd64",
"build_date": "2020-10-20T11:54:38Z",
"compiler": "gc",
"git_commit": "f37f03116e0a2d1d5874af94c3a8c0b470ce2382",
"go_version": "go1.15.2",
"operating_system": "linux"
}
}
<more logs>
```
**NOTE: This also updates the GitHub Actions pipelines to use our `make` commands for building the binary.**
> feat: use new version pkg

- DOCS.md
- Makefile
- cmd/vela-kaniko/main.go
The first part of this PR is modifying the environment variables and file path arguments we support for the plugin.
The idea is to introduce one consistent standard that all plugins should be able to support 👍 
For environment variables, this pattern will be:
* `PARAMETER_<parameter_name>`
* `<plugin_name>_<parameter_name>`
Using the `event` parameter for this plugin as an example:
* `PARAMETER_EVENT`
* `KANIKO_EVENT`
For file path arguments, this pattern will be:
* `/vela/parameters/<plugin_name>/<parameter_name>`
* `/vela/secrets/<plugin_name>/<parameter_name>`
Using the `event` parameter again for this plugin as an example:
* `/vela/parameters/kaniko/event`
* `/vela/secrets/kaniko/event`
The second part of this PR is modifying the `DOCS.md` file in the root of the repository to more …
> refactor: update variable configuration for consistency

- Dockerfile
Upgrade Kaniko to the latest release `v1.3.0`
The release notes can be found below:
https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.3.0
> chore: upgrade to latest kaniko release

- .github/README.md
- .vela/template.yml
- Dockerfile
- LICENSE
- Makefile
- cmd/vela-kaniko/build.go
- cmd/vela-kaniko/build_test.go
- cmd/vela-kaniko/command.go
- cmd/vela-kaniko/command_test.go
- cmd/vela-kaniko/image.go
- cmd/vela-kaniko/image_test.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
- cmd/vela-kaniko/registry.go
- cmd/vela-kaniko/registry_test.go
- cmd/vela-kaniko/repo.go
- cmd/vela-kaniko/repo_test.go
- version/version.go
This is a general housekeeping task.
I used VS code's search and replace:
* Search: `Copyright (c) 2020`
* Replace: `Copyright (c) 2021`
At the top of every file, the new copyright statement now looks like:
```
// Copyright (c) 2021 Target Brands, Inc. All rights reserved.
```
> chore: update copyright year to 2021

- Dockerfile
This change will upgrade Kaniko to the latest release (`v1.5.2`):
https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.5.2
The release notes can be found below:
https://github.com/GoogleContainerTools/kaniko/blob/master/CHANGELOG.md#v152-release-2021-03-30
> chore: upgrade kaniko to v1.5.2

- Dockerfile
Between the `v1.3.0` and `v1.5.x` releases, the image path for Kaniko has changed.
This ensures we're adopting the latest standards for the Kaniko images being published:
https://github.com/GoogleContainerTools/kaniko/releases/tag/v1.5.2
> fix: debug image path for Kaniko

- cmd/vela-kaniko/command.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- go.sum
This invokes the `version` subcommand for the `kaniko` CLI as a part of the plugin output.
To test this, you can checkout this branch and run the following:
```sh
make build; make docker-build; make docker-test
```
This should lead to output that looks like:
```sh
time="2021-05-07T13:53:05Z" level=info msg="Vela Kaniko Plugin" code="https://github.com/go-vela/vela-kaniko" docs="https://go-vela.github.io/docs/plugins/registry/pipeline/kaniko" registry="https://hub.docker.com/r/target/vela-kaniko"
{
"canonical": "v0.6.0",
"major": 0,
"minor": 6,
"patch": 0,
"metadata": {
"architecture": "amd64",
"build_date": "2021-05-07T08:52:46Z",
"compiler": "gc",
"git_commit": "eeea105fed7fc11bda4b43a00edfc49a5c982968",
"go_version": "go1.16.3",
"operating_system": "linux"
}
}
$ /kaniko/executor version …
```
> feat: output kaniko version for troubleshooting

- .github/README.md
- .vela/template.yml
- Dockerfile
- LICENSE
- Makefile
- cmd/vela-kaniko/build.go
- cmd/vela-kaniko/build_test.go
- cmd/vela-kaniko/command.go
- cmd/vela-kaniko/command_test.go
- cmd/vela-kaniko/image.go
- cmd/vela-kaniko/image_test.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
- cmd/vela-kaniko/registry.go
- cmd/vela-kaniko/registry_test.go
- cmd/vela-kaniko/repo.go
- cmd/vela-kaniko/repo_test.go
- version/version.go
This is a general housekeeping task.
Used VS code's search and replace:
• Search: Copyright (c) 2021
• Replace: Copyright (c) 2022
At the top of every file, the new copyright statement now looks like:
`// Copyright (c) 2022 Target Brands, Inc. All rights reserved.`
> chore: update copyright year to 2022

- DOCS.md
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
- cmd/vela-kaniko/registry.go
This adds support to the kaniko plugin to instruct Kaniko to push or pull from insecure (http) docker registries.
This is useful for folks running Vela without a way to secure their registries with SSL and also for "home labbers" might be running Vela at home.
Should close https://github.com/go-vela/community/issues/470
Adds new string-slice parameters:
- PARAMETER_INSECURE_REGISTRIES
- KANIKO_INSECURE_REGISTRIES
With support from loading the value from disc at:
- /vela/parameters/kaniko/insecure_registries
- /vela/secrets/kaniko/insecure_registries
---
While #470 above, notes the 3 command line flags, the [kaniko docs](https://github.com/GoogleContainerTools/kaniko#--insecure-registry) would leave me to believe that if you want to allow pushing and/or pulling from an insecure registry, …
> feat: support insecure registries when pushing & pulling

- DOCS.md
- cmd/vela-kaniko/image.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
Kaniko supports a `--customPlatform` flag to allow creation of images
with a different platform than the default, which is a platform derived
from the build host.
The `--customPlatform` feature doesn't provide any cross-compilation
support by itself, and only platforms which the underlying build host
is able to provide will work correctly.
This commit provides a `custom_platform` plugin parameter which,
when supplied, will provide a value for the `--customPlatform`
argument for `/kaniko/executor`. There is no attempt to verify that
the platform requested is supported by the build host.
Should close go-vela/community#477
Example:
```
steps:
- name: publish_hello-world_amd64
image: vela-plugins/kaniko:vCustomPlatform
pull: always
parameters:
repo: vela/hello-world
custom_platform: …
```
> feat: Add ability to set `--customPlatform` flag

- DOCS.md
- cmd/vela-kaniko/image.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
Kaniko supports a --customPlatform flag to allow creation of images
with a different platform than the default, which is a platform derived
from the build host.
The --customPlatform feature doesn't provide any cross-compilation
support by itself, and only platforms which the underlying build host
is able to provide will work correctly.
This commit provides a custom_platform plugin parameter which,
when supplied, will provide a value for the --customPlatform
argument for /kaniko/executor. There is no attempt to verify that
the platform requested is supported by the build host.
Closes go-vela/community#477
Backport of go-vela/vela-kaniko#110
Example:
```
steps:
- name: publish_hello-world_amd64
image: vela-plugins/kaniko:vCustomPlatform
pull: always
parameters:
repo: vela/hello-world …
```
> feat: Add ability to set --customPlatform flag

- cmd/vela-kaniko/build.go
- cmd/vela-kaniko/build_test.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
- cmd/vela-kaniko/repo.go
this PR makes the following changes:
- remove validation from the build tag produced by the user 
- users should be able to provide whatever tag they wish. 
- move `auto_tag` functionality to the plugin preparation, prior to producing the `Command` used by the kaniko binary.
- fixes up tests
the build tag should only be validated when the user attempts to use it via `auto_tag` to publish
therefore, we should look for `auto_tag` when preparing the plugin configurations, use it to configure the repo tags, _then_ validate those repo tags 
(most of which we are already doing, just out of order) 
closes https://github.com/go-vela/community/issues/701
> fix: configure repo tags before validation

- DOCS.md
- cmd/vela-kaniko/build.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
closes https://github.com/go-vela/community/issues/739
> feat: add support for use-new-run

- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
Kaniko deprecated the --snapshotMode flag in favor of --snapshot-mode.  This change gets rid of the warning ```level=warning msg="Flag --snapshotMode is deprecated. Use: --snapshot-mode"``` in current release.
> fix: change snapshotMode to snapshot-mode

- .github/workflows/build.yml
- .github/workflows/prerelease.yml
- .github/workflows/publish.yml
- .github/workflows/reviewdog.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- go.mod
using same pattern as we do on core repos: see https://github.com/go-vela/server/tree/main/.github/workflows for example
> chore(ci/go): update ci to use core repos pattern

- .github/README.md
- .golangci.yml
- .vela/template.yml
- Dockerfile
- LICENSE
- Makefile
- cmd/vela-kaniko/build.go
- cmd/vela-kaniko/build_test.go
- cmd/vela-kaniko/command.go
- cmd/vela-kaniko/command_test.go
- cmd/vela-kaniko/image.go
- cmd/vela-kaniko/image_test.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
- cmd/vela-kaniko/registry.go
- cmd/vela-kaniko/registry_test.go
- cmd/vela-kaniko/repo.go
- cmd/vela-kaniko/repo_test.go
- version/version.go
ref: https://github.com/go-vela/community/issues/747
- replaces code file license headers with SPDX header (see https://spdx.dev/ids/#why); this removes copyright + year
- update golangci-lint rule to ensure code file enforcement
- use first commit date for copyright year and updates year in other select places
- format is changed to match "Copyright [yyyy] [name of copyright owner]" as shown here: https://www.apache.org/licenses/LICENSE-2.0.html
> chore(license): update source code headers + copyright year

- DOCS.md
- cmd/vela-kaniko/main.go
support for a third-party integration that writes shared credentials to the managed-auth filepath.
> enhance: add arg for third party integration credentials

- cmd/vela-kaniko/main.go
These changes will allow the following pipeline:
```yaml
steps:
- name: kaniko
image: target/vela-kaniko:latest
parameters:
build_args:
list: one,two,three
foo: bar
dry_run: true
registry: docker.company.com
repo: docker.company.com/myapp
```
Today, if using the slice input, the above would interpret the build args as `--build-arg list=one --build-arg two --build-arg three --build-arg foo=bar`.
> enhance: support map type for build args

- .github/workflows/reviewdog.yml
- cmd/vela-kaniko/build.go
- cmd/vela-kaniko/main.go
- cmd/vela-kaniko/plugin.go
- cmd/vela-kaniko/plugin_test.go
- cmd/vela-kaniko/repo.go
Adding a few seemingly useful flags for the Kaniko executor:
- https://github.com/GoogleContainerTools/kaniko#flag---compressed-caching
- https://github.com/GoogleContainerTools/kaniko#flag---log-timestamp
- https://github.com/GoogleContainerTools/kaniko#flag---ignore-path
> enhance(flags): add compressed caching, log timestamp, and ignore path flags
